--set database sql syntax pgs true
-- do not add data if it is already added.

CREATE SEQUENCE IF NOT EXISTS seq1 AS INTEGER START WITH 9;
CREATE SEQUENCE IF NOT EXISTS seq2 AS INTEGER START WITH 4;
CREATE SEQUENCE IF NOT EXISTS seq3 AS INTEGER START WITH 6;

CREATE TABLE IF NOT EXISTS SalesItem (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY unique,
    title VARCHAR(31) NOT NULL,
    text VARCHAR(255) NOT NULL,
    price FLOAT,
    date_val DATE NOT NULL
);

INSERT INTO SalesItem (id, title, text, price, date_val) VALUES (1, 'Bananas', 'From Columbia', 1,  DATE '2021-05-01')
ON CONFLICT (id) DO UPDATE SET
id = excluded.id, title = excluded.title, text = excluded.text, price = excluded.price, date_val = excluded.date_val;
INSERT INTO SalesItem (id, title, text, price, date_val) VALUES (2, 'Mangos', 'From Thailand', 3,  DATE '2021-04-01')
ON CONFLICT (id) DO UPDATE SET
id = excluded.id, title = excluded.title, text = excluded.text, price = excluded.price, date_val = excluded.date_val;
INSERT INTO SalesItem (id, title, text, price, date_val) VALUES (3, 'Kiwis', 'From LAV', 5,  DATE '2021-03-01')
ON CONFLICT (id) DO UPDATE SET
id = excluded.id, title = excluded.title, text = excluded.text, price = excluded.price, date_val = excluded.date_val;
INSERT INTO SalesItem (id, title, text, price, date_val) VALUES (4, 'Oranges', 'From Morocco', 3,  DATE '2021-02-01')
ON CONFLICT (id) DO UPDATE SET
id = excluded.id, title = excluded.title, text = excluded.text, price = excluded.price, date_val = excluded.date_val;
INSERT INTO SalesItem (id, title, text, price, date_val) VALUES (5, 'Apples', 'From Poland', 2,  DATE '2021-01-01')
ON CONFLICT (id) DO UPDATE SET
id = excluded.id, title = excluded.title, text = excluded.text, price = excluded.price, date_val = excluded.date_val;
INSERT INTO SalesItem (id, title, text, price, date_val) VALUES (6, 'Figs', 'From Greece', 7,  DATE '2020-12-01')
ON CONFLICT (id) DO UPDATE SET
id = excluded.id, title = excluded.title, text = excluded.text, price = excluded.price, date_val = excluded.date_val;
INSERT INTO SalesItem (id, title, text, price, date_val) VALUES (7, 'Coconuts', 'From Indonesia', 4,  DATE '2020-11-01')
ON CONFLICT (id) DO UPDATE SET
id = excluded.id, title = excluded.title, text = excluded.text, price = excluded.price, date_val = excluded.date_val;
INSERT INTO SalesItem (id, title, text, price, date_val) VALUES (8, 'Lotuses', 'From Vietnam', 9,  DATE '2020-10-01')
ON CONFLICT (id) DO UPDATE SET
id = excluded.id, title = excluded.title, text = excluded.text, price = excluded.price, date_val = excluded.date_val;


CREATE TABLE IF NOT EXISTS Filter (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL
);

INSERT INTO Filter (id, title) VALUES (1, 'Filter 1') ON CONFLICT (id) DO UPDATE SET id = excluded.id, title = excluded.title;
INSERT INTO Filter (id, title) VALUES (2, 'Filter 2') ON CONFLICT (id) DO UPDATE SET id = excluded.id, title = excluded.title;
INSERT INTO Filter (id, title) VALUES (3, 'Filter 3') ON CONFLICT (id) DO UPDATE SET id = excluded.id, title = excluded.title;

CREATE TABLE IF NOT EXISTS SubFilter (
     filter_id BIGINT,
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     filter_type INTEGER,
     text VARCHAR(255) DEFAULT '',
     date_val DATE,
     CONSTRAINT fk_filter FOREIGN KEY (filter_id) REFERENCES Filter(id)
);

INSERT INTO SubFilter (filter_id, id, filter_type, text, date_val) VALUES (1, 1, 1, 'Bana', null) ON CONFLICT (id) DO UPDATE SET filter_id = excluded.filter_id, id = excluded.id, filter_type = excluded.filter_type, text = excluded.text, date_val = excluded.date_val;
INSERT INTO SubFilter (filter_id, id, filter_type, text, date_val) VALUES (1, 2, 1, 'nana', null) ON CONFLICT (id) DO UPDATE SET filter_id = excluded.filter_id, id = excluded.id, filter_type = excluded.filter_type, text = excluded.text, date_val = excluded.date_val;
INSERT INTO SubFilter (filter_id, id, filter_type, text, date_val) VALUES (1, 3, 2, 'Col', null) ON CONFLICT (id) DO UPDATE SET filter_id = excluded.filter_id, id = excluded.id, filter_type = excluded.filter_type, text = excluded.text, date_val = excluded.date_val;
INSERT INTO SubFilter (filter_id, id, filter_type, text, date_val) VALUES (2, 4, 11, ' ', '2021-03-17') ON CONFLICT (id) DO UPDATE SET filter_id = excluded.filter_id, id = excluded.id, filter_type = excluded.filter_type, text = excluded.text, date_val = excluded.date_val;
INSERT INTO SubFilter (filter_id, id, filter_type, text, date_val) VALUES (3, 5, 10, '10', null) ON CONFLICT (id) DO UPDATE SET filter_id = excluded.filter_id, id = excluded.id, filter_type = excluded.filter_type, text = excluded.text, date_val = excluded.date_val;
